ZSH=$HOME/.oh-my-zsh
MY_ZSH=$HOME/config/zsh
ZSH_THEME="my"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"

plugins=() # zsh-syntax-highlighting
source $ZSH/oh-my-zsh.sh

# atuo complete
zstyle :compinstall filename '~/.zshrc'
autoload -Uz compinit
compinit

# 使我的配置文件生效
for config_file ($MY_ZSH/lib/*(N)) source $config_file


